    // Generated by CoffeeScript 1.4.0
    var Test, test, test2;

    Test = (function() {
      function Test() {}
      Test.prototype.a = [];
      return Test;
    })();

    test = new Test();
    test.a.push('b');

    test2 = new Test();
    console.log(test2.a);
