// Generated by CoffeeScript 1.4.0
var Texy;

module.exports = Texy = (function() {

  function Texy() {}

  Texy.CONTENT_MARKUP = 17;

  Texy.CONTENT_REPLACED = 16;

  Texy.CONTENT_TEXTUAL = 15;

  Texy.CONTENT_BLOCK = 14;

  Texy.prototype.test = function() {
    return true;
  };

  return Texy;

})();
